"""Adjust in fields

Revision ID: 506dc290ed36
Revises: f25170f21cd6
Create Date: 2021-12-15 16:25:53.006759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '506dc290ed36'
down_revision = 'f25170f21cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('deployment', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('deployment', sa.Column('assets', mysql.LONGTEXT(), nullable=True))
    op.alter_column('deployment', 'workflow_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=200),
               nullable=True)
    op.alter_column('deployment', 'request_cpu',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('deployment', 'limit_cpu',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('deployment_target', sa.Column('namespace', sa.String(length=100), nullable=False))
    op.add_column('deployment_target', sa.Column('volume_path', sa.String(length=250), nullable=False))
    op.alter_column('deployment_target', 'authentication_info',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=500),
               type_=sa.String(length=2500),
               existing_nullable=True)
    op.alter_column('deployment_target', 'target_type',
               existing_type=mysql.ENUM('SUPERVISOR', 'KUBERNETES', 'DOCKER', 'MARATHON', collation='utf8_unicode_ci'),
               type_=sa.Enum('DOCKER', 'KUBERNETES', 'MARATHON', 'SUPERVISOR', name='DeploymentTargetTypeEnumType'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployment_target', 'target_type',
               existing_type=sa.Enum('DOCKER', 'KUBERNETES', 'MARATHON', 'SUPERVISOR', name='DeploymentTargetTypeEnumType'),
               type_=mysql.ENUM('SUPERVISOR', 'KUBERNETES', 'DOCKER', 'MARATHON', collation='utf8_unicode_ci'),
               existing_nullable=False)
    op.alter_column('deployment_target', 'authentication_info',
               existing_type=sa.String(length=2500),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=500),
               existing_nullable=True)
    op.drop_column('deployment_target', 'volume_path')
    op.drop_column('deployment_target', 'namespace')
    op.alter_column('deployment', 'limit_cpu',
               existing_type=sa.String(length=20),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('deployment', 'request_cpu',
               existing_type=sa.String(length=20),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('deployment', 'workflow_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=200),
               nullable=False)
    op.drop_column('deployment', 'assets')
    op.drop_column('deployment', 'port')
    op.drop_column('deployment', 'name')
    # ### end Alembic commands ###
