"""Add fields

Revision ID: f25170f21cd6
Revises: dac2243ad0ba
Create Date: 2021-12-14 16:01:48.132292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f25170f21cd6'
down_revision = 'dac2243ad0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_image', sa.Column('description', sa.String(length=200), nullable=False))
    op.add_column('deployment', sa.Column('model_name', sa.String(length=200), nullable=False))
    op.add_column('metric_value', sa.Column('deployment_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_metric_value_deployment_id'), 'metric_value', ['deployment_id'], unique=False)
    op.create_foreign_key('fk_metric_value_deployment_id', 'metric_value', 'deployment', ['deployment_id'], ['id'])
    op.drop_column('metric_value', 'tma_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_value', sa.Column('tma_data', mysql.LONGTEXT(collation='utf8_unicode_ci'), nullable=True))
    op.drop_constraint('fk_metric_value_deployment_id', 'metric_value', type_='foreignkey')
    op.drop_index(op.f('ix_metric_value_deployment_id'), table_name='metric_value')
    op.drop_column('metric_value', 'deployment_id')
    op.drop_column('deployment', 'model_name')
    op.drop_column('deployment_image', 'description')
    # ### end Alembic commands ###
